#!/usr/bin/perl -w
## Edits
# Brad Sawatzky <brads@jlab.org>   07 Feb 2017
# 01 Oct 2021 (Provakar Datta) Modified for Hall A HV_logging (SBS)

sub usage() {
  my $output="";
  $output.="Usage: $0 <name_of_sub-system>\n";
  $output.="\tThis converts a *.hvc file used with the Hall A HV GUI and\n";
  $output.="\toutputs an '*.dictionary' format file for the EPICS logging tool to accept.\n";
  $output.="\tTakes one argument which is the name of the sub-system.\n";
  $output.="\tFollowing three options are available:\n";
  $output.="\t1. BB_HV : This includes HV channel info for BB Spectrometer (i.e. BBCal, BBHodo, BBGem, GRINCH)\n";
  $output.="\t2. SBS_HV : This includes HV channel info for SBS Spectrometer (i.e. HCal etc.)\n";
  $output.="\t3. LHRS_HV : This includes HV channel info for LHRS\n"; 
  $output.="\tExample execution for BB_HV sub-system : ./make_HV_dict.pl BB_HV\n";
  return "$output\n";
}

if($#ARGV != 0) {
  print usage();
  exit 1;
}

$subSys = $ARGV[0];

my $infile=$ENV{$subSys}.'/HV.hvc';
my $outfile=$subSys.'.dictionary';


## Load the *.hvc file
my @channels;
open(INF, "<$infile") or die "Can't open '$infile': $!\n";
while(<INF>) {
  next if(/^\s*#/);
  next if(/^\s*$/);

  chomp;
  my @f = split;

  push(@channels, [$f[0], sprintf("HAHV%d:%02d:%03d", $f[1], $f[2], $f[3])]);
}
close INF;


my $comments="# Generated by $0\n";
$comments.="# " . localtime() . "\n";
$comments.="# Input file was: $infile\n";
$comments.="# + is Left and Bottom\n";
$comments.="\n";
$comments.="# " . "-"x160 . "\n";
$comments.="# Variable Name        |          RunType    | Read-rate [s] |    Sub-System    |        Comment\n";
$comments.="# " . "-"x160 . "\n";
$comments.="\n";


## Write the 'epics.dictionary' format file
open(OUTF, ">$outfile") or die "Can't open '$outfile': $!\n";
print OUTF $comments;
foreach my $ch (@channels) {
  foreach my $v ( qw(V0Setr VMon IMon) ) {
    printf(OUTF  "%-24s  %-20s  %-20s  %-20s %s\n",
        sprintf("%s:%s",$ch->[1],$v),       # EPCIS channel name
        "all",                              # 'Runtype'    [all, allm]
        "HV",                               # 'Read rate:  HV='HV, start of run only'
        "$subSys",                               # "Expert/Owner"
        $ch->[0] . " $v"                    # Comment field with the channel name
    );
  }
}

exit 0;
